# NumPy Arrays

In [122]:
import numpy as np

## **Q1- Create one dimensional array using python list**
- Data type needs to be float64 
- Print dtype, shape, size, dimension, and memory consumption of each element and total array

In [ ]:
#create

In [20]:
# print

Data type =  float64
Shape =  (5,)
Size =  5
Dimension =  1
Each element memory size =  8
Total array memory size =  40


## **Q2- Create two dimensional array using python list**
- Print dtype, shape, size, dimension, and memory consumption of each element and total array

In [ ]:
#create

In [19]:
#print

Data type =  int64
Shape =  (2, 4)
Size =  8
Dimension =  2
Each element memory size =  8
Total array memory size =  64


## **Q3- Create a length of 10 integer array filled with zeros**

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Q4- Create a 4X5 floating point array filled with 1s**

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## **Q5- Create a 3x3 identity matrix**
- Data type: int

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## **Q6- Create a one dimensional array of length 10**
- Use numpy function arange to create the array
- Assign new value (12) at the index of 5,6,7

In [ ]:
#create

In [37]:
#asign

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## **Q7- Create a 3x3 array**
- a. Use numpy function arange and reshape() to create the array
- b. Select the first two rows of array
- c. Select the second row but only the first two columns 
- d. Select the third column but only the first two rows
- e. Select the first column only
- f. Assign the new value 15 to the last element of third row and third column and print the array

In [58]:
# a.
# code

In [59]:
#print

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
# b.


array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# c.


array([4, 5])

In [64]:
# d.


array([3, 6])

In [65]:
# e.


array([[1],
       [4],
       [7]])

In [66]:
# f.


In [67]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 15]])

## **Q8- Create two arrays of 3x1 and 3x3 shape**
- Join both the arrays horizontally and store the result in variable concat
- Split the concat array into 2x3 and 1x3 shape

In [91]:
#code

In [92]:
#print

array([[97],
       [98],
       [99]])

In [93]:
#code

In [94]:
#print

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
#code

In [96]:
#print

array([[97,  1,  2,  3],
       [98,  4,  5,  6],
       [99,  7,  8,  9]])

[array([[97,  1,  2,  3],
        [98,  4,  5,  6]]),
 array([[99,  7,  8,  9]])]

[array([[97,  1],
        [98,  4],
        [99,  7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

[array([[97,  1,  2],
        [98,  4,  5],
        [99,  7,  8]]),
 array([[3],
        [6],
        [9]])]