# B104020024 HW_1 --9/20

In [1]:
import numpy as np

In [2]:
list1=np.arange(5)
list2=np.array(list1,dtype=np.float64)

In [3]:
print("Data type = ",list2.dtype)
print("Shape =  ",list2.shape)
print("Size = ",list2.size)
print("Dimension =  ",list2.ndim)
print("Each element memory size =  ",list2.itemsize)
print("Total array memory size = ",list2.size*list2.itemsize)


Data type =  float64
Shape =   (5,)
Size =  5
Dimension =   1
Each element memory size =   8
Total array memory size =  40


In [4]:
list3=np.arange(8)
list4=np.array(list3,dtype=np.int64)
list4=list4.reshape(2,4)

In [5]:
print("Data type = ",list4.dtype)
print("Shape =  ",list4.shape)
print("Size = ",list4.size)
print("Dimension =  ",list4.ndim)
print("Each element memory size =  ",list4.itemsize)
print("Total array memory size = ",list4.size*list4.itemsize)

Data type =  int64
Shape =   (2, 4)
Size =  8
Dimension =   2
Each element memory size =   8
Total array memory size =  64


In [6]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
q4=np.ones(20,dtype=float)
q4.reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
q5=np.identity(3,dtype=int)
print(q5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
x=np.arange(10,dtype=int)

In [10]:
x[5:8]=12
x

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [11]:
q7=np.arange(1,10,dtype=int).reshape(3,3)

In [12]:
q7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
q7[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
q7[1:2,:2]

array([[4, 5]])

In [15]:
q7[:2,2:3]

array([[3],
       [6]])

In [16]:
q7[:3,:1]

array([[1],
       [4],
       [7]])

In [17]:
q7[2:3,2:3]=15
q7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 15]])

In [18]:
q81=np.arange(97,100).reshape(3,1)
q81

array([[97],
       [98],
       [99]])

In [19]:
q82=np.arange(1,10).reshape(3,3)
q82

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
q8new=np.hstack([q81,q82])
q8new

array([[97,  1,  2,  3],
       [98,  4,  5,  6],
       [99,  7,  8,  9]])

In [21]:
np.vsplit(q8new,[2])

[array([[97,  1,  2,  3],
        [98,  4,  5,  6]]),
 array([[99,  7,  8,  9]])]

In [22]:
np.hsplit(q8new,[2])

[array([[97,  1],
        [98,  4],
        [99,  7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [23]:
np.hsplit(q8new,[3])

[array([[97,  1,  2],
        [98,  4,  5],
        [99,  7,  8]]),
 array([[3],
        [6],
        [9]])]