In [6]:
# import relate packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

import warnings
warnings.filterwarnings('ignore')

In [7]:
# run before starting to answer
Boston = datasets.load_boston()
boston = np.concatenate((Boston['data'],Boston['target'].reshape(506,1)),axis=1)
boston = pd.DataFrame(boston, columns= ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 
                                     'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'])

- Ques-1: Overview of the data
    - a. print the number of samples in the boston data
    - b. print the number of features in the boston data
    - c. view first 5 rows of the boston data

In [8]:
# 1-a
a_1=len(boston)
print('The number of samples in the boston data is',a_1)

The number of samples in the boston data is 506


In [9]:
# 1-b
b_1=len(boston.columns)
print('The number of features in the boston data is',b_1)

The number of features in the boston data is 14


In [10]:
# 1-c
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

- Ques 2: Features matrix and target array
    - a. separate the boston data into X and y (hint y= MEDV)
    - b. the shape of X
    - c. the shape of y
    - d. print X and y

In [11]:
# 2-a
X = boston.drop('MEDV', axis = 1)
y = boston['MEDV']

In [12]:
# 2-b
print(X.shape)

(506, 13)


In [13]:
# 2-c
print(y.shape)

(506,)


In [14]:
# 2-d
print(X)
print(y)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       1

- Ques 3: Linear regression
    - a. import the linear regression class
    - b. fit the boston data with a linear regression using hyperparameter intercept term
    - c. print the coefficient of features
    - d. print the coefficient of intercept term

In [15]:
# 3-a
from sklearn.linear_model import LinearRegression

In [16]:
# 3-b
b_3 = LinearRegression(fit_intercept=True).fit(X,y)

In [17]:
# 3-c
b_3.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [18]:
# 3-d
b_3.intercept_

36.459488385089855

- Ques 4: Predict and measure the model performance using mean squared error 
- a. import the mean_squared_error class from metrics module of sklearn library
- b. predict MEDV for the boston data
- c. evaluate the mean squared error between predict MEDV and real MEDV

In [19]:
# 4-a
from sklearn.metrics import mean_squared_error

In [20]:
# 4-b
y_predict = b_3.predict(X)
print(y_predict)

[30.00384338 25.02556238 30.56759672 28.60703649 27.94352423 25.25628446
 23.00180827 19.53598843 11.52363685 18.92026211 18.99949651 21.58679568
 20.90652153 19.55290281 19.28348205 19.29748321 20.52750979 16.91140135
 16.17801106 18.40613603 12.52385753 17.67103669 15.83288129 13.80628535
 15.67833832 13.38668561 15.46397655 14.70847428 19.54737285 20.8764282
 11.45511759 18.05923295  8.81105736 14.28275814 13.70675891 23.81463526
 22.34193708 23.10891142 22.91502612 31.35762569 34.21510225 28.02056414
 25.20386628 24.60979273 22.94149176 22.09669817 20.42320032 18.03655088
  9.10655377 17.20607751 21.28152535 23.97222285 27.6558508  24.04901809
 15.3618477  31.15264947 24.85686978 33.10919806 21.77537987 21.08493555
 17.8725804  18.51110208 23.98742856 22.55408869 23.37308644 30.36148358
 25.53056512 21.11338564 17.42153786 20.78483633 25.20148859 21.7426577
 24.55744957 24.04295712 25.50499716 23.9669302  22.94545403 23.35699818
 21.26198266 22.42817373 28.40576968 26.99486086 26.0

In [21]:
# 4-c
mean_squared_error(y_predict, y, squared = True)

21.894831181729202

- Ques 5: Model validation using holdout dataset
 - a. import the train_test_split class
 - b. split the boston data into X_train, X_test, y_train ,and y_test with 50% in each set (Note: set random_state=1)
 - c. fit the train data with a linear regression
 - d. predict MEDV for the test data
 - e. evaluate the mean squared error between predict MEDV and real MEDV of test data

In [38]:
# 5-a

from sklearn.model_selection import train_test_split

In [39]:
# 5-b

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 1)

In [40]:
# 5-c
c_5 = LinearRegression()
c_5.fit(X_train, y_train)

LinearRegression()

In [41]:
# 5-d

y_test_predict = c_5.predict(X_test)

In [42]:
# 5-e

mean_squared_error(y_test_predict, y_test, squared = True)

22.839287038640244

- Ques 6: Model validation using cross-validation
    - a. import the cross_val_score class from model_selection module of sklearn library
    - b. use Scikit-Learn's cross_val_score to split the boston data into five
fold and evaluate the model fit by 'neg_mean_squared_error'
    - c. use Scikit-Learn's cross_val_score to split the boston data into five
fold and evaluate the model fit by 'neg_mean_absolute_error'

In [43]:
# 6-a
from sklearn.model_selection import cross_val_score

In [45]:
# 6-b and c

b_6=cross_val_score(c_5, X, y, cv = 5, scoring = 'neg_mean_squared_error')
c_6=cross_val_score(c_5, X, y, cv = 5, scoring = 'neg_mean_absolute_error')
print(b_6)
print(c_6)

[-12.46030057 -26.04862111 -33.07413798 -80.76237112 -33.31360656]
[-2.62190565 -3.90725478 -4.386606   -5.57073637 -4.76333993]


- Ques 7 : Classification problem
    - a. load the iris data from sklearn.datasets
    - b. set data as iris_X, target as iris_y
    - c. instantiate iris_model using GaussianNB model from naive_bayes library of sklearn 
    and fit the model to the data
    - d. predict the iris_X data and evaluate the model fit using accuracy_score function
    - e. split the iris data into five fold and evaluate the model fit

In [46]:
from sklearn.metrics import accuracy_score

In [47]:
# 7-a
from sklearn.datasets import load_iris
iris = load_iris()

In [48]:
# 7-b
iris_X = iris.data
iris_y = iris.target

In [49]:
# 7-c
from sklearn.naive_bayes import GaussianNB
iris_model = GaussianNB()
iris_model.fit(iris_X, iris_y)

GaussianNB()

In [50]:
# 7-d
y_predict = iris_model.predict(iris_X)
accuracy_score(y_predict, iris_y)

0.96

In [53]:
# 7-e

score = cross_val_score(iris_model , iris_X, iris_y, cv = 5)
print(score)
score.mean()

[0.93333333 0.96666667 0.93333333 0.93333333 1.        ]


0.9533333333333334