In [1]:
import numpy as np

In [2]:
np.version.version

'1.21.5'

In [3]:
np.random.randint(0,10,(3,3))

array([[8, 0, 4],
       [8, 5, 4],
       [3, 2, 8]])

In [5]:
a=np.array([[2,4],[1,3]])

In [6]:
a.shape

(2, 2)

In [7]:
np.random.seed(0)

In [27]:
x1=np.random.rand(6)
x2=np.random.rand(3,4)
x3=np.random.rand(3,5)

In [28]:
x2

array([[0.50831545, 0.16684751, 0.77905102, 0.8649333 ],
       [0.41139672, 0.13997259, 0.03322239, 0.98257496],
       [0.37329075, 0.42007537, 0.05058812, 0.36549611]])

In [29]:
x=np.arange(10)

In [30]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5]

array([0, 1, 2, 3, 4])

In [32]:
x[5:]

array([5, 6, 7, 8, 9])

In [33]:
x[4:7]

array([4, 5, 6])

In [37]:
x[5::-2]

array([5, 3, 1])

In [44]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
x2[0:2,0:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [46]:
grid=np.arange(1,10).reshape(3,3)

In [47]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
x=np.array([1,2,3])

In [69]:
x1=x.reshape(1,3)

In [70]:
x.ndim

1

In [71]:
x1

array([[1, 2, 3]])

In [72]:
x1.ndim

2

In [73]:
x

array([1, 2, 3])

In [86]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [87]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [88]:
z=np.array([99,99,99])

In [89]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [95]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [97]:
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
z=np.array([[99],[99],[99]])

In [106]:
z

array([[99],
       [99],
       [99]])

In [107]:
np.hstack([z,grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6],
       [99,  7,  8,  9]])

In [108]:
x=np.array([1,2,3,99,99,3,2,1])

In [109]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [113]:
np.split(x,[3,5,6])

[array([1, 2, 3]), array([99, 99]), array([3]), array([2, 1])]

In [114]:
grid=np.arange(16).reshape(4,4)

In [115]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
upper,lower=np.vsplit(grid,[2])

In [118]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
