In [1]:
import numpy as np

In [6]:
rand=np.random.RandomState(42)
x=rand.randint(100,size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [7]:
x[2],x[3],x[7]

(14, 71, 86)

In [11]:
ind =[2,7,3]
x[ind]

array([14, 86, 71])

In [14]:
ind =np.array([[3,7],[4,5]])

In [17]:
ind

array([[3, 7],
       [4, 5]])

In [18]:
x[ind]

array([[71, 86],
       [60, 20]])

In [19]:
x=np.arange(12).reshape(3,4)

In [20]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
row=np.array([0,1,2])
col=np.array([2,1,3])

In [28]:
x[row,col]

array([ 2,  5, 11])

In [25]:
x[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [26]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x[2,[2,0,2]]

array([10,  8, 10])

In [32]:
x[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [33]:
mask=np.array([1,0,1,0],dtype=bool)

In [34]:
mask

array([ True, False,  True, False])

In [38]:
x[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [40]:
x=np.arange(10)
i=np.array([2,1,8,4])

In [41]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
print(i)

[2 1 8 4]


In [43]:
x[i]

array([2, 1, 8, 4])

In [44]:
x[i]=99

In [45]:
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [47]:
x[i]-=10

In [48]:
x

array([ 0, 89, 89,  3, 89,  5,  6,  7, 89,  9])

In [49]:
i=np.argsort(x)

In [50]:
i

array([0, 3, 5, 6, 7, 9, 1, 2, 4, 8], dtype=int64)

In [51]:
x

array([ 0, 89, 89,  3, 89,  5,  6,  7, 89,  9])

In [52]:
x=np.array([99,88,77,66,55,44,33,22,11])

In [53]:
x

array([99, 88, 77, 66, 55, 44, 33, 22, 11])

In [60]:
np.partition(x,3)

array([22, 11, 33, 44, 55, 88, 66, 77, 99])

In [61]:
np.partition(x,[3,3])

array([22, 11, 33, 44, 55, 88, 66, 77, 99])

In [62]:
x

array([99, 88, 77, 66, 55, 44, 33, 22, 11])

In [63]:
values=[('rex',9,81.9),('rex',9,81.9),('rex',9,81.9)]

In [65]:
F=np.array(values,datatype)

NameError: name 'datatype' is not defined