In [1]:
import numpy as np
import pandas as pd

# Hierarchical Indexing

## Multiple Indexed Series

In [2]:
# Using Python Tuples as Keys

index = [('California', 2000), ('California', 2010),
        ('New York', 2000),('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]

In [3]:
population = [33871648, 37253956,
             18976457, 19378102,
             20851820, 25145561]

In [5]:
pop = pd.Series(population, index=index)
print(pop)

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64


In [6]:
pop[('New York', 2000): ('Texas', 2010)]

(New York, 2000)    18976457
(New York, 2010)    19378102
(Texas, 2000)       20851820
(Texas, 2010)       25145561
dtype: int64

In [7]:
# Converting python tuple multi-index into pandas multi-index

index = pd.MultiIndex.from_tuples(index)
print(index)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )


In [8]:
pop = pop.reindex(index)
print(pop)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


In [9]:
pop['New York': 'Texas']

New York  2000    18976457
          2010    19378102
Texas     2000    20851820
          2010    25145561
dtype: int64

In [10]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [11]:
# Converting Multi-index series into indexed dataframe using unstack()
pop_df = pop.unstack()
print(pop_df)

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561


In [12]:
# What if we want to add another column of demographic data (under 18)

pop_df = pd.DataFrame({'total': pop,
                      'under18': [9267089, 9284094,
                                 4687371, 4318033,
                                 5906301, 6879014]})
print(pop_df)

                    total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687371
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014


In [13]:
f_u18 = pop_df['under18']/pop_df['total']

In [15]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

# Methods of MultiIndex Creation

- List
- Dictionary
- MultiIndex constructors

## Creating multi-index by List

In [16]:
df = pd.DataFrame(np.random.rand(4,2),
                 index=[['a', 'a', 'b', 'b'], [1,2,1,2]],
                 columns=['data1', 'data2'])

print(df)

        data1     data2
a 1  0.224705  0.665547
  2  0.460511  0.736936
b 1  0.320914  0.298263
  2  0.489936  0.992498


## Creating MultiIndex by Dictionary

In [17]:
data = {('California', 2000): 33871648,
            ('California', 2010): 37253956,
            (  'New York', 2000): 18976457,
            (  'New York', 2010): 19378102,
            (     'Texas', 2000):20851820,
            (     'Texas', 2010):25145561}

data

{('California', 2000): 33871648,
 ('California', 2010): 37253956,
 ('New York', 2000): 18976457,
 ('New York', 2010): 19378102,
 ('Texas', 2000): 20851820,
 ('Texas', 2010): 25145561}

In [19]:
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

## Explicit MultiIndex Constructors

In [21]:
# from the list of arrays
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1,2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [22]:
# from the list of tuples
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [23]:
# From a cartesian product of single series
pd.MultiIndex.from_product([['a', 'b'], [1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

## MultiIndex level names

In [24]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [27]:
pop.index.names = ['state', 'year']
print(pop)

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


## MultiIndex for Columns

In [36]:
# Creating medical data
# Hierarchical indices and columns

index = pd.MultiIndex.from_product([[2013,2014], [1,2]],
                                  names = ['year', 'visit'])

columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'],
                                      ['HR', 'Temp']],
                                    names=['patient', 'measurement'])

In [37]:
# Create some data

data = np.round(np.random.randn(4,6), 1) # round of 1
print(data)

[[-0.8  0.6  0.8 -0.3  1.3 -1.3]
 [ 1.2  0.2 -0.8  1.2 -1.6 -0.8]
 [-1.4 -0.9 -0.1  0.3  1.3  0.3]
 [ 0.2 -1.5 -0.2 -0.3  1.1 -0.1]]


In [38]:
data[:,::2] *=10
print(data)

[[ -8.    0.6   8.   -0.3  13.   -1.3]
 [ 12.    0.2  -8.    1.2 -16.   -0.8]
 [-14.   -0.9  -1.    0.3  13.    0.3]
 [  2.   -1.5  -2.   -0.3  11.   -0.1]]


In [39]:
data +=37

In [40]:
print(abs(data))

[[29.  37.6 45.  36.7 50.  35.7]
 [49.  37.2 29.  38.2 21.  36.2]
 [23.  36.1 36.  37.3 50.  37.3]
 [39.  35.5 35.  36.7 48.  36.9]]


In [41]:
# Create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
print(health_data)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       29.0  37.6  45.0  36.7  50.0  35.7
     2       49.0  37.2  29.0  38.2  21.0  36.2
2014 1       23.0  36.1  36.0  37.3  50.0  37.3
     2       39.0  35.5  35.0  36.7  48.0  36.9


In [42]:
# Access the data of a person
health_data['Guido']

measurement    HR  Temp
year visit             
2013 1       45.0  36.7
     2       29.0  38.2
2014 1       36.0  37.3
     2       35.0  36.7

In [43]:
# Access the data of a person from a particular year
health_data.loc[2013, 'Guido']

measurement    HR  Temp
visit                  
1            45.0  36.7
2            29.0  38.2

In [44]:
# Recover patient heart rate
health_data['Guido', 'HR']

year  visit
2013  1        45.0
      2        29.0
2014  1        36.0
      2        35.0
Name: (Guido, HR), dtype: float64

In [46]:
# Access first two rows and first four columns
health_data.iloc[:2,:4]

patient       Bob       Guido      
measurement    HR  Temp    HR  Temp
year visit                         
2013 1       29.0  37.6  45.0  36.7
     2       49.0  37.2  29.0  38.2

In [48]:
# Acces the heart rate of Guido using slicing
health_data.loc[:,('Guido', 'HR')]

year  visit
2013  1        45.0
      2        29.0
2014  1        36.0
      2        35.0
Name: (Guido, HR), dtype: float64

In [49]:
# Access the heart rate of all patients first visit using tuple of multiple 
# indices

health_data.loc[(:,1), (:, 'HR')]

SyntaxError: invalid syntax (2608783577.py, line 4)

In [50]:
# IndexSlice

idx = pd.IndexSlice
health_data.loc[idx[:,1], idx[:,'HR']]

patient       Bob Guido   Sue
measurement    HR    HR    HR
year visit                   
2013 1       29.0  45.0  50.0
2014 1       23.0  36.0  50.0

In [51]:
# Access the heart rate of Bob's first visit in 2014 using IndexSlice

health_data.loc[idx[2014,1], idx['Bob', 'HR']]

23.0

In [52]:
# Access the heart rate and temperature of Bob and sue's first visit 
# in 2014 using IndexSlice

health_data.loc[idx[2014,1], idx[['Bob', 'Sue'], 'HR':'Temp']]

patient  measurement
Bob      HR             23.0
         Temp           36.1
Sue      HR             50.0
         Temp           37.3
Name: (2014, 1), dtype: float64

# Data Aggregations on Multi-Indices

In [53]:
health_data

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       29.0  37.6  45.0  36.7  50.0  35.7
     2       49.0  37.2  29.0  38.2  21.0  36.2
2014 1       23.0  36.1  36.0  37.3  50.0  37.3
     2       39.0  35.5  35.0  36.7  48.0  36.9

In [54]:
# Average out the measurement in the two visits each year
data_mean = health_data.mean(level='year') # row wise aggregation
print(data_mean)

patient       Bob       Guido          Sue       
measurement    HR  Temp    HR   Temp    HR   Temp
year                                             
2013         39.0  37.4  37.0  37.45  35.5  35.95
2014         31.0  35.8  35.5  37.00  49.0  37.10


C:\Users\cccm\AppData\Local\Temp\ipykernel_6108\2225863166.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean = health_data.mean(level='year')


In [55]:
data_mean.mean(axis=1, level='measurement')

C:\Users\cccm\AppData\Local\Temp\ipykernel_6108\4139955395.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean.mean(axis=1, level='measurement')


measurement         HR       Temp
year                             
2013         37.166667  36.933333
2014         38.500000  36.633333

# Combining Datasets: Concatenate

In [57]:
# one dimensional array

x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# Two dimensional array
x = [[1,2],
    [3,4]]
np.concatenate([x,x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

# Concatenation in Series and DataFrame
- pd.concat()

In [60]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4,5,6])

pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [3]:
# Create the Data for Dataframe

df1 = pd.DataFrame(np.arange(0,9).reshape(3,3),
                  index=[1,2,3],
                  columns=['a','b','c'])
print(df1)

   a  b  c
1  0  1  2
2  3  4  5
3  6  7  8


In [4]:
df2 = pd.DataFrame(np.arange(9,18).reshape(3,3),
                  index=[4,5,6],
                  columns=['a','b','c'])
print(df2)

    a   b   c
4   9  10  11
5  12  13  14
6  15  16  17


In [63]:
# Combining two dataframe
pd.concat([df1, df2])

a   b   c
1   0   1   2
2   3   4   5
3   6   7   8
4   9  10  11
5  12  13  14
6  15  16  17

In [5]:
df3 = pd.DataFrame(np.arange(18,27).reshape(3,3),
                  index=[1,2,3],
                  columns=['d','e','f'])
print(df3)

    d   e   f
1  18  19  20
2  21  22  23
3  24  25  26


In [65]:
# Combine two dataframe column wise
pd.concat([df1,df3], axis=1)

a  b  c   d   e   f
1  0  1  2  18  19  20
2  3  4  5  21  22  23
3  6  7  8  24  25  26

**What if we have duplicate indices**

In [2]:
# Create a dataframe 
df4 = pd.DataFrame(np.arange(9,18).reshape(3,3),
                  index=[1,2,3],
                  columns=['a','b','c'])

print(df4)

    a   b   c
1   9  10  11
2  12  13  14
3  15  16  17


In [7]:
print(df1)

   a  b  c
1  0  1  2
2  3  4  5
3  6  7  8


In [6]:
# concat preserves the duplicate indices
pd.concat([df1, df4])

a   b   c
1   0   1   2
2   3   4   5
3   6   7   8
1   9  10  11
2  12  13  14
3  15  16  17

In [8]:
# concat column wise
pd.concat([df1, df4], axis=1)

a  b  c   a   b   c
1  0  1  2   9  10  11
2  3  4  5  12  13  14
3  6  7  8  15  16  17

In [9]:
# If we want to ignore the index
pd.concat([df1, df4], ignore_index=True)

a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17

In [10]:
# We want to specify the label for data source

pd.concat([df1, df4], keys=['df1', 'df4'])

a   b   c
df1 1   0   1   2
    2   3   4   5
    3   6   7   8
df4 1   9  10  11
    2  12  13  14
    3  15  16  17

In [12]:
# Combine data where some of the columns are common

df5 = pd.DataFrame(np.arange(27,36).reshape(3,3),
                 index=[4,5,6],
                 columns=['b','c','d'])

print(df5)

    b   c   d
4  27  28  29
5  30  31  32
6  33  34  35


In [13]:
pd.concat([df1, df5])

a   b   c     d
1  0.0   1   2   NaN
2  3.0   4   5   NaN
3  6.0   7   8   NaN
4  NaN  27  28  29.0
5  NaN  30  31  32.0
6  NaN  33  34  35.0

In [14]:
# performing intersection / or getting the output where columns are same

pd.concat([df1, df5], join='inner')

b   c
1   1   2
2   4   5
3   7   8
4  27  28
5  30  31
6  33  34

In [17]:
# Specify the resulting output as the same of a particular column
pd.concat([df1,df5.reindex(columns=df1.columns)])

a   b   c
1  0.0   1   2
2  3.0   4   5
3  6.0   7   8
4  NaN  27  28
5  NaN  30  31
6  NaN  33  34

# Combining Datasets: Merge and Join

- Using pd.merge() function implements a number of types of joins
- one-to-one (when the values are unique in keys of both the datasets)
- many-to-one (when the values of one of a key is duplicate)
- many-to-many (when the values of both the dataset key's are duplicate)

## One-to-one joins

In [19]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'group': ['Accounting', 'Engineering', 'Engineering', 'HR' ]})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                   'hire_date': [2004, 2008, 2012, 2014]})

In [20]:
display(df1, df2)

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [22]:
df3 = pd.merge(df1,df2)
print(df3)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


## Many-to-One joins

In [23]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                   'supervisor': ['Carly', 'Guido', 'Steve']})
print(df4)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


In [24]:
pd.merge(df3,df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

## Many-to-Many Joins

In [25]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 
                              'Engineering', 'HR', 'HR'],
                   'skills': ['math', 'spreadsheets', 'coding', 'linux', 
                              'spreadsheets', 'organization']})

print(df5)

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


In [26]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [27]:
pd.merge(df1,df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

**We want to combine two datasets with different column name but same values**

- Using left_on and right_on keywords to specify the two column names

In [29]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'salary': [70000, 80000, 120000, 9000]})
print(df3)

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue    9000


In [30]:
display(df1, df3)

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue    9000

In [31]:
pd.merge(df1, df3, left_on='employee', right_on='name')

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue    9000

In [32]:
# drop the duplicate column

pd.merge(df1, df3, left_on='employee', right_on='name').drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR    9000

**We want to merge the data based on Index**

In [34]:
display(df1, df2)

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [35]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display(df1a, df2a)

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

- To merge the dataset based on index we use left_index and right_index keyword

In [36]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [37]:
print(df3)

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue    9000


- We want to combine the data using index and column 

In [38]:
pd.merge(df1a, df3, left_index=True, right_on='name')

group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue    9000

## What if the values appear in one column key but not the other 

In [39]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                   'food': ['fish', 'beans', 'bread']})

df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                   'drink': ['Wine', 'beer']})
display(df6, df7)

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

name drink
0    Mary  Wine
1  Joseph  beer

In [40]:
pd.merge(df6, df7) # by default it is giving the output based on inner join

name   food drink
0  Mary  bread  Wine

In [41]:
# Intersection join using how='inner'
pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  Wine

In [42]:
# Union join using how = 'outer'
pd.merge(df6, df7, how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  Wine
3  Joseph    NaN  beer

## Overlapping Column Names

**What if we have conflicting column names**

In [43]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'rank': [1,2,3,4]})

df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'rank': [3,1,4,2]})

display(df8, df9)

name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [44]:
pd.merge(df8, df9, on='name')

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [45]:
pd.merge(df8, df9, on='name', suffixes=['_L', '_R'])

name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2