In [1]:
import numpy as np

In [2]:
np.version.version

'1.21.5'

In [3]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [4]:
np?

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a = np.array([1,2,3], dtype = 'float32')

In [9]:
a.shape

(3,)

In [12]:
b = np.array([[1,2], [3,4]])

In [13]:
b.shape

(2, 2)

In [14]:
b

array([[1, 2],
       [3, 4]])

## Creating Arrays from Scratch

In [15]:
np.zeros(10, dtype=int) # single dimension array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# multi-dimension array

np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [18]:
#[start, stop, step]

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# create an array with a linear sequence

np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
# create a 3*3 array of uniformly distributed random values between 0 and 1

np.random.random((3,3))

array([[0.93567619, 0.03061141, 0.09652672],
       [0.71995063, 0.2576688 , 0.20001451],
       [0.59460935, 0.3345925 , 0.20838724]])

In [21]:
# create a 3x3 array of normal distribution with mean 0 and standard deviation 1

np.random.normal(0, 1, (3,3))

array([[-0.38081394, -1.2691748 , -0.31351274],
       [ 0.27691726,  1.07764466,  0.4851485 ],
       [ 0.77069434,  0.25578742,  0.959191  ]])

In [22]:
# creating array of random integers between 0 to 10

np.random.randint(0, 10, (3, 3))

array([[8, 1, 9],
       [6, 5, 9],
       [1, 8, 2]])

## Basics of NumPy Arrays
- Attributes of arrays
- Indexing of arrays 
- Slicing of arrays
- Reshaping of arrays
- Concatenation and splitting of arrays

In [23]:
np.random.seed(0)

In [24]:
x1 = np.random.randint(10, size=6) # one dimension array
x2 = np.random.randint(10, size=(3,4)) # two- dimension array
x3 = np.random.randint(10, size=(3,4,5)) # three-dimension array

In [26]:
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


In [27]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(3, 4)
(3, 4, 5)


In [28]:
x1

array([5, 0, 3, 3, 7, 9])

In [29]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [31]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
60


In [32]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)

int32
int32
int32


In [33]:
print(x1.itemsize)
print(x2.itemsize)
print(x3.itemsize)

4
4
4


In [34]:
print(x1.nbytes)
print(x2.nbytes)
print(x3.nbytes)

24
48
240


1. [X] Attributes of arrays
2. [ ] Indexing of arrays 
3. [ ] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenation and splitting of arrays

In [36]:
x1 # indexing starts with zero and end by N-1

array([5, 0, 3, 3, 7, 9])

In [37]:
x1[0]

5

In [38]:
x1[5]

9

In [39]:
x1[-1]

9

In [40]:
x1[-2]

7

In [41]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [42]:
x2[0,0]

3

In [43]:
x2[2,1]

6

In [44]:
x2[2,-1]

7

In [45]:
# Modify the value of an array element

x2[0,0] = 12

In [46]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [47]:
x1.dtype

dtype('int32')

In [48]:
x1

array([5, 0, 3, 3, 7, 9])

In [49]:
x1[0] = 3.14

In [50]:
x1

array([3, 0, 3, 3, 7, 9])

1. [X] Attributes of arrays
2. [X] Indexing of arrays 
3. [ ] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenation and splitting of arrays

In [53]:
x = np.arange(10)

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# x[start:stop:step]

x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [56]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Access middle subarrays

x[4:7]

array([4, 5, 6])

In [60]:
# access every other element after index 1 

x[1::3]

array([1, 4, 7])

In [61]:
# every other element starting from index 1 and stop at 8

x[1:8:2]

array([1, 3, 5, 7])

In [62]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# reverse the array by using -1 in steps

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
# reverse the array from a particular index

x[5::-2]

array([5, 3, 1])

In [65]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [67]:
# x[start,stop(n-1), step]
x2[0:2,0:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [69]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [68]:
# every rows, every other column

x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [70]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [71]:
# reversing all the rows

x2[::-1,:]

array([[ 1,  6,  7,  7],
       [ 7,  6,  8,  8],
       [12,  5,  2,  4]])

In [72]:
# reversing all the columns

x2[:,::-1]

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7],
       [ 7,  7,  6,  1]])

In [73]:
# reversing rows and columns

x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

1. [X] Attributes of arrays
2. [X] Indexing of arrays 
3. [X] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenation and splitting of arrays

- using reshape() method to transform the data

In [80]:
grid = np.arange(1, 10).reshape(3,3)

In [81]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
x = np.array([1,2,3])

In [86]:
x.ndim

1

In [89]:
x1 = x.reshape(3,1) #row vector via reshape

In [90]:
x1.ndim

2

In [91]:
x1.shape

(3, 1)

1. [X] Attributes of arrays
2. [X] Indexing of arrays 
3. [X] Slicing of arrays
4. [X] Reshaping of arrays
5. [ ] Concatenation and splitting of arrays

In [92]:
# Joining and splitting of arrays

x = np.array([1,2,3])
y = np.array([3,2,1])

In [93]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [94]:
z = np.array([99,99,99])

In [111]:
np.concatenate([x, y, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)

In [98]:
# combining two-dimensional arrays

grid = np.arange(1,7).reshape(2,3)

In [99]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.concatenate([grid, grid]) #by default axis=0/ rows

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [101]:
np.concatenate([grid, grid], axis=1) #column wise combination

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- Combining mixed dimensional arrays
- vstack, hstack

In [102]:
x

array([1, 2, 3])

In [103]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [106]:
z = np.array([[99], [99]])

In [107]:
z

array([[99],
       [99]])

In [108]:
np.hstack([z, grid]) #horizontally stack arrays

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

- Splitting of the arrays
- Using split, vsplit, hsplit

In [112]:
x = np.array([1,2,3,99,99,3,2,1])

In [113]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [114]:
np.split(x, [3,5]) # result will leads to N+1 subarrays

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [115]:
grid = np.arange(16).reshape(4,4)

In [116]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
# vertical split

upper, lower = np.vsplit(grid, [2])

In [118]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [119]:
left, right = np.hsplit(grid, [2])

In [120]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


1. [X] Attributes of arrays
2. [X] Indexing of arrays 
3. [X] Slicing of arrays
4. [X] Reshaping of arrays
5. [X] Concatenation and splitting of arrays